nodeLinker: node-modules

yarnPath: "./.yarn/releases/yarn-3.0.2.cjs"
npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: ${NPM_TOKEN}
    npmAlwaysAuth: true

npmScopes:
  "dracula":
    npmRegistryServer: "https://npm.pkg.github.com/"
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}