// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CCard: typeof import('./src/components/CCard.vue')['default']
    CHeading: typeof import('./src/components/CHeading.vue')['default']
    CLink: typeof import('./src/components/CLink.vue')['default']
    CSect: typeof import('./src/components/CSect.vue')['default']
    CText: typeof import('./src/components/CText.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    MCView: typeof import('./src/views/MCView.vue')['default']
    PrivacyView: typeof import('./src/views/PrivacyView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
