[[redirects]]
    from = "/js/index.outbound-links.js"
    to = "https://plausible.io/js/plausible.outbound-links.js"
    status = 200
[[redirects]]
    from = "/api/event"
    to = "https://plausible.io/api/event"
    status = 202
[[headers]]
    for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"